### PR TITLE
batch1_devel updates to the CMSSW 45117 PR

### PR DESCRIPTION
**Pull request by slava77**
This is to keep track of feature changes that were added in batch1_devel, but did not enter the CMSSW main PR during its review.
The goal is to at least see if merge conflicts arise and then decide what to do with them.

### CODE REVIEW

**Comment by ariostas** [comment]
I just synced the devel and batch3/realfiles branches. There were a ton of conflicts that needed to be resolved. I'll run the CI to make sure everything went well.

/run all

**Comment by ariostas** [comment]
There were a couple of small issues, but everything should be fine now.

/run all

**Comment by ariostas** [comment]
I changed the base branch a couple times and now GitHub is not confused

**Comment by ariostas** [comment]
> Uhm, but it now looks like it doesn't recognize any changes/contributions already in [CMSSW_14_1_0_pre3_LST_X_LSTCore_realfiles](https://github.com/SegmentLinking/cmssw/tree/CMSSW_14_1_0_pre3_LST_X_LSTCore_realfiles)

That's normal, it's only listing the new commits on the `_devel` branch. Or do you mean something else?

**Comment by slava77** [comment]
> That's normal, it's only listing the new commits on the `_devel` branch. Or do you mean something else?

I meant the diffs show as if everything in this test PR is new (44K lines, all "green"), while I'd expect to see only new stuff from devel; not sure if this is due to the conflicts

**Comment by ariostas** [comment]
> I meant the diffs show as if everything in this test PR is new (44K lines, all "green"), while I'd expect to see only new stuff from devel; not sure if this is due to the conflicts

Oh I see. Yeah, I imagine this is due to the conflicts

**Comment by ariostas** [comment]
Just had to change the base branch so that GitHub would show the right commits. I'm compiling a list of changes that were introduced here that will need to be rebased since the CMSSW PR is (hopefully) close to being merged.

**Comment by VourMa** [comment]
Closing this, as all the developments have been successfully merged.

**Pull request closed without merging**
