### PR TITLE
batch10 of updates for LST integration in CMSSW 

### PR DESCRIPTION
**Pull request by slava77**
move 24834.704 from relval_Run4 to to relval_gpu; update description/comment
to address
- https://github.com/cms-sw/cmssw/pull/45117#discussion_r1846213397  : move 24834.704 from relval_Run4 to to relval_gpu
- https://github.com/cms-sw/cmssw/pull/45117#discussion_r1844143282 to mention in README that LST is Phase-2
- https://github.com/cms-sw/cmssw/pull/45117#discussion_r1844129351 update comment from 2026 to Run4

### CODE REVIEW

**Comment by slava77** [comment]
the tests a mostly superfluous in this case.
The modified files are not parsed in the CI tests

@VourMa @ariostas please check if I implemented this OK, and merge if it looks OK (I didn't want to self-merge without some time left to discuss)

**Comment by slava77** [comment]
> and merge if it looks OK

make sure to do "squash and merge"

**Review by VourMa — APPROVED** [review]
Looks good to me, I can merge during our meeting today, in case there is anything to discuss.

**Comment by ariostas** [comment]
Also looks good to me. I disabled merge commits since for a while we'll probably want to stick with squash-merges or rebase-merges.

**Comment by slava77** [comment]
> I disabled merge commits since for a while we'll probably want to stick with squash-merges or rebase-merges.

is this per branch or per repository?

**Comment by ariostas** [comment]
> is this per branch or per repository?

Per repository. Do you think it would inconvenience other developments? I'll see if it can be done per branch.

**Comment by ariostas** [comment]
Oh yeah, now it's only for this branch

**Pull request merged**
