### PR TITLE
continuing migration to SoA: upd TC, migrate T3s, T5s, pT3s and pT5s ...

### PR DESCRIPTION
**Pull request by slava77**
- started with followups to comments to #90 : simplify implementation of TC SoAs

### CODE REVIEW

**Comment by slava77** [comment]
timing seems OK on cgpu-1 L4  (CI will show the CPU part)
reference cb84b9c25e6 
image
vs this PR 1bbe66374e0
image

**Comment by slava77** [comment]
compared to the check-point after T3 migration, the time after T5 migration is smaller in a single stream, but that seems unrelated to T5 (hits column is lower)
image

**Comment by slava77** [comment]
for a change, even the CPU variant showed a reduction
image

In the past couple of commits I also tried to move around the includes to be more minimal (e.g Event.h having only SoA and H/D collection declarations, instead of the full files with kernels), although it may be more of a reshuffle

**Comment by slava77** [comment]
the time on L4 didn't change much this time, after pT3, pT5 migration
image

**Comment by slava77** [comment]
I marked this ready for review
(comparisons on cgpu-1 GPU look OK)

**Comment by slava77** [comment]
> I marked this ready for review 

@ariostas 
In case this looks good perhaps this can be merged first.

how would you like to proceed?

**Review by ariostas — APPROVED** [review]
I went through the changes and everything looks good. The plots and timings also look good.

There's a couple of things you did here that I didn't do on my PR (removing "inGPU" from kernel names and having HostCollections on separate headers), so I'll add another commit to mine to make them consistent.

**Comment by slava77** [comment]
> There's a couple of things you did here that I didn't do on my PR (removing "inGPU" from kernel names and having HostCollections on separate headers), so I'll add another commit to mine to make them consistent.

The `InGPU` and `v2` removal in the kernel names was another set of comments; so I mixed up a bit along the way; doesn't have to be in the rest of SoA migration.
The separate files for the HostCollection was a part of comments to my TC SoA PR.

**Pull request merged**
