### PR TITLE
Replace Second dBeta Cut with DNN

### PR DESCRIPTION
**Pull request by GNiendorf**
Work in progress, may adjust the cut value. The second dBeta cut is very tight and causes quite a loss of pT5 efficiency (especially in a few bins outside the barrel as you can see below, eta -1.5). This PR has a looser cut right now to address this issue, which you will probably see with the increase in FR.

### CODE REVIEW

**Comment by GNiendorf** [comment]
May tighten further to 95.0% depending on the results, seems like this is still a loose cut.

/run all

**Comment by GNiendorf** [comment]
To illustrate the issue with the second delta beta cut, here is its current signal efficiency on 100% matched tracks as a function of abs(eta):

[0.996, 0.995, 0.996, 0.996, _**0.915, 0.839, 0.912, 0.968,**_ 0.994, 0.999] : efficiency
[0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5] : abs(eta) bins

You can see that at around abs(eta) 1.25 the efficiency drops to a low of **84%**.

**Comment by slava77** [comment]
> To illustrate the issue with the second delta beta cut, here is its current signal efficiency on 100% matched tracks as a function of abs(eta):
> 
> [0.996, 0.995, 0.996, 0.996, _**0.915, 0.839, 0.912, 0.968,**_ 0.994, 0.999] : efficiency [0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5] : abs(eta) bins
> 
> You can see that at around abs(eta) 1.25 the efficiency drops to a low of **84%**.

I'm curious if there is an issue (bug) in the math for 2S layers.
please break this down to T5s starting from B1 and B2, if possible.
Another check could be to set `runQuintupletdBetaCutBBEE` and separately `runQuintupletdBetaCutBBBB` to return `true` to localize the issue.

**Comment by slava77** [comment]
> I'm curious if there is an issue (bug) in the math for 2S layers.

at a glance, the code is written in a way to account for the full spread in dBeta in the possible range along the strip length. It could be some sign flip or min/max swap that leads to this inefficiency.

**Comment by GNiendorf** [comment]
The issue is in `runQuintupletdBetaCutBBEE`.

**Comment by GNiendorf** [comment]
Fixed in PR #124 hopefully.

**Comment by GNiendorf** [comment]
Honestly, I'm just going to close this PR and start fresh considering how much #124 changes the efficiency plots.

**Pull request closed without merging**
