### PR TITLE
Replace Second Delta Beta Cut with DNN

### PR DESCRIPTION
**Pull request by GNiendorf**
On the 1000 event RelVal plots (not shown here yet) this PR leads to a higher efficiency at a lower FR. Considering that issue #123 was fixed though, I think it makes sense to only merge this PR if I can replace both delta beta cuts at a performance improvement. Leaving this PR as a draft for now.

Continuation of PR #122, although I heavily downsample 80% matched tracks during training in this PR to get better overall performance and a DNN cut more similar to the existing delta beta cuts.

### CODE REVIEW

**Comment by GNiendorf** [comment]
@slava77 It looks like this method of downsampling 80% tracks works for the second delta beta cut, but not for the first delta beta cut. It seems like the more underlying issue is network size when training on the larger sample. If I increase network size substantially it fixes the issue without having to downsample tracks, although I think it would take a substantial amount of effort to make a larger model that has competitive timing to the current hybrid approach. Closing this PR for now. I'm going to shift my focus to work on loading the weights properly and hopefully getting a timing improvement with lower precision weights.

**Comment by slava77** [comment]
> [404795f](https://github.com/SegmentLinking/cmssw/commit/404795f9ef76583c9d56eb9a4ee5bab8e0bd2d39)
> 
> Here is the big dnn code with associated training notebook for future reference.

two more layers and double the hidden features; right?
How much slower is it?

**Comment by GNiendorf** [comment]
> two more layers and double the hidden features; right? How much slower is it?

The number of parameters increases by a factor of ~7.6x, the t5 timing increases by a factor of 12x (1ms->12ms). I didn't check to see if a smaller network fixes the issue though.

**Comment by slava77** [comment]
> > two more layers and double the hidden features; right? How much slower is it?
> 
> The number of parameters increases by a factor of ~7.6x, the t5 timing increases by a factor of 12x (1ms->12ms). I didn't check to see if a smaller network also fixes the issue though.

running a profiler may help.
2x more features would 2^3 in matrix computation. x2 layers it's 16x. While I thought that in 1ms the DNN computation was not the leading term. 
I suspect memory constraints, that the new weights don't fit anymore in the SM.
Perhaps only 50% more hidden features would fit (at least one per layer matrix)

**Pull request closed without merging**
