### PR TITLE
alpaka modernise/improve for batch4

### PR DESCRIPTION
**Pull request by slava77**
- use cms::alpakatools::once_per_block  69debc2bac724a1baf6a9aadfd60e396c862c975  https://github.com/cms-sw/cmssw/pull/45117#discussion_r1681612338
- geometry ::get optimize https://github.com/cms-sw/cmssw/pull/45117#discussion_r1681702267 https://github.com/cms-sw/cmssw/pull/45117#discussion_r1681702518 07e0f4013fa4169aa33b88cf55c1b36933bce154
- remove `Vec3D createVec` https://github.com/cms-sw/cmssw/pull/45117#discussion_r1682855978 d5e0b699a4fe8cf0aa72b462d623f26018f37d2e

### CODE REVIEW

**Comment by slava77** [comment]
I'm not sure if the static checks CI call is controlled by `/run linter`. The log says it timed out.

**Comment by slava77** [comment]
looks like the same symptoms
image

**Comment by VourMa** [comment]
@slava77 Will you be adding more things to this one?

**Comment by slava77** [comment]
> @slava77 Will you be adding more things to this one?

I wanted to, later today. It's a draft because of that.
From the things I recall, it will be more about buffers (wait, getPointerNative, memcopy) to have the branch name more match what's in it.
Do you see some conflicting points?

**Comment by VourMa** [comment]
> Do you see some conflicting points?

No, all good, just trying to keep track of all the comments and who does what. Thanks!

**Review by VourMa — APPROVED** [review]

**Pull request merged**
