### PR TITLE
Improvements to the LST workflows and small general LST fixes

### PR DESCRIPTION
**Pull request by VourMa**
In this PR I have:
- Moved the LST workflows to use the latest default geometry (D110)
- Made the `0.704` run on a GPU only if there is one, otherwise fall back to CPU.
- Replaced the custom binary search function with `std::lower_bound`.
- Made a couple more minor fixes that need to be done (e.g. using `MessageLogger` instead of `printf`, renamings, etc.)
- Got rid of the warning about the `SeedStopInfo` size mismatch between the `TrackCandidate` and the `TrajectorySeed` collections.

### CODE REVIEW

**Comment by VourMa** [comment]
Everything seems ok, so I will proceed to the CMSSW PR with this.

**Comment by slava77** [comment]
should this be made non-draft?

**Comment by VourMa** [comment]
> should this be made non-draft?

Yes, sorry, I forgot to do it.

**Comment by VourMa** [comment]
> the CMSSW PR tests are suggestive that we should try to not mix changes in the algorithm code and redefinition of workflows: it's not possible to run comparisons.

I had no idea about such a thing. If there is a need to refactor, I will do it, but I would like to avoid it and keep it in mind for the next time.

**Comment by slava77** [comment]
> keep it in mind for the next time.

I think this should be enough

**Pull request merged**
