### PR TITLE
Update to CMSSW_14_1_0_pre5

### PR DESCRIPTION
**Pull request by ariostas**
This PR is to update our "master" branch to CMSSW_14_1_0_pre5, so that we can move things into a common library.

Apart from the commits that pre5 brings, I added one to update the setup scripts.

### CODE REVIEW

**Comment by slava77** [comment]
how would this look like in the "master"? will it be a single merge commit not visible in the diffs?
A way to check could be to resync SegmentLinking/cmssw:master and have a look.

The goal/hope is that the diffs visible now will get recognized and not show up in the PR itself.

**Comment by ariostas** [comment]
> how would this look like in the "master"? will it be a single merge commit not visible in the diffs?

Yeah, it shows up as a single merge commit. You can check here:
https://github.com/SegmentLinking/cmssw/compare/master...SegmentLinking:cmssw:update_to_pre5

Also, the CI failed because the target branch is still in pre3, but it did run the code with pre5.

**Comment by slava77** [comment]
> Yeah, it shows up as a single merge commit. You can check here:
> [master...SegmentLinking:cmssw:update_to_pre5](https://github.com/SegmentLinking/cmssw/compare/master...SegmentLinking:cmssw:update_to_pre5)

that's not quite the same; once it goes to the `realfiles` there will be another merge commit in there; hopefully it's not going to confuse the system.
... well, the cost will be a reset and force push, so, not a big deal.

**Comment by ariostas** [comment]
If you prefer one fewer merge commit I could push directly, but either way it should be fine.

**Comment by slava77** [comment]
> If you prefer one fewer merge commit I could push directly, but either way it should be fine.

it may be a solution.

However, there is a failure in cmssw side:
`ModuleNotFoundError: No module named 'Configuration.ProcessModifiers.ticl_v5_cff'`

is it an issue in the CI mixing pre3 reference and pre5?
should we add a special case to setup a cmsrel for the test topic branch (if it's different from the baseline)?

**Comment by ariostas** [comment]
> is it an issue in the CI mixing pre3 reference and pre5?

Yeah, the issue is that only does one `cmsrel`. Running `git cms-init` takes forever (I've never been sure why), so it might not be good to try to do two.

**Comment by slava77** [comment]
> > is it an issue in the CI mixing pre3 reference and pre5?
> 
> Yeah, the issue is that only does one `cmsrel`. Running `git cms-init` takes forever (I've never been sure why), so it might not be good to try to do two.

perhaps it's worth to make a PR of `update_to_pre5` to a plain pre5. Shouldn't the CI work out of the box in that case?

**Pull request closed without merging**
