### PR TITLE
Remove user-defined destructors, make vector moves useful, rename kernels

### PR DESCRIPTION
**Pull request by VourMa**
Dealing with:
- Removing user-defined destructors:
  - https://github.com/cms-sw/cmssw/pull/45117#discussion_r1718839698
  - https://github.com/cms-sw/cmssw/pull/45117#discussion_r1718840680
  - https://github.com/cms-sw/cmssw/pull/45117#discussion_r1718841494
  - https://github.com/cms-sw/cmssw/pull/45117#discussion_r1718853146
  - https://github.com/cms-sw/cmssw/pull/45117#discussion_r1718875317
  - https://github.com/cms-sw/cmssw/pull/45117#discussion_r1718877766
  - https://github.com/cms-sw/cmssw/pull/45117#discussion_r1718891455
- Making vector moves useful:
  - https://github.com/cms-sw/cmssw/pull/45117#discussion_r1718836997
  - https://github.com/cms-sw/cmssw/pull/45117#discussion_r1718840557
  - https://github.com/cms-sw/cmssw/pull/45117#discussion_r1718841360
- Renaming kernels:
  - https://github.com/cms-sw/cmssw/pull/45117#discussion_r1718961361

### CODE REVIEW

**Comment by slava77** [comment]
I hope the static checks will finish some time soon

**Comment by VourMa** [comment]
> I hope the static checks will finish some time soon

I will try to keep my laptop close for as much as I can to follow up on anything that may come up.

**Comment by ariostas** [comment]
I think it's weird that they suggested to remove user-defined destructors given that 4.13 in the [Coding Rules](https://cms-sw.github.io/cms_coding_rules.html) says:

> For a class, definition of any of the following requires definition of all five: destructor, copy constructor, copy assignment operator, move constructor, and move assignment operator. (*)

**Comment by ariostas** [comment]
The changes look good to me. There will be some minor conflicts with #84, but I'll fix them after this gets merged.

**Review by ariostas — APPROVED** [review]

**Pull request merged**
