### PR TITLE
Improvements to the README

### PR DESCRIPTION
**Pull request by VourMa**
After getting feedback from various people in the group, I tried to improve the README with more (accurate) instructions.

### CODE REVIEW

**Comment by VourMa** [comment]
@mmasciov @YonsiG Could you check that I have taken your comments properly into account?

**Comment by YonsiG** [comment]
The new commands work properly for me. Thank you for the update!

**Comment by VourMa** [comment]
@aashayarora Please comment whether the updated instructions worked for you or not. If they did, then this is good to be merged.

**Comment by VourMa** [comment]
Confirming that this worked fine out of the box. The PR is ready to be merged.

**Review by YonsiG — APPROVED** [review]

**Pull request merged**
