### PR TITLE
batch8 of updates for LST integration in CMSSW

### PR DESCRIPTION
**Pull request by slava77**
This should cover the required (and trivial=required) changes

#### 0f7b8ef5eb44a7dfc52f90a0c428dfaa5e83b748
- Removed `allocBufWrapper` and cache toggle.
- Fixed failing header test.
- Improved view creation.
- Removed `devAcc_`.
- Applied trivial fixes.
- Applied required renamings.

#### 387d52b142e981b636538f61f0563011e1c52aff
  - workflows;
  - enums;
  - compilation;
  - moving LSTOutputConverter to edm::stream::EDProducer;
  - facelifting the `LSTEvent`;
  - change the way to not construct the lstProducerTask;
  - use `std::numbers::pi_v<float>` for π;
  - merge `get*` and `get*InCMSSW` functions;
  - rename `lst_INF`.

### CODE REVIEW

**Comment by slava77** [comment]
or did I jump the gun too early with this combo PR and a squash is needed.
This will add 22 commits to our upstream PR which has 183 (or is it 184 commits) --> 205, leaving us with max 35 before hitting a hard threshold.

**Comment by VourMa** [comment]
> or did I jump the gun too early with this combo PR and a squash is needed.

I don't think you jumped the gun, we can still squash in this one before merging. Let's coordinate later today on this, merge, and I will also start resolving comments.

**Comment by ariostas** [comment]
We could just start squash-merging batches instead of "normal" merging

**Pull request merged**
