### PR TITLE
Devel updates to LST

### PR DESCRIPTION
**Pull request by ariostas**
This PR adds the updates to LST/LSTCore that were developed while the CMSSW integration PR was being reviewed.

(We'll think of a better title and description when submitting to the upstream CMSSW repo.)

### CODE REVIEW

**Comment by ariostas** [comment]
Here's a draft for the CMSSW PR. @slava77 @VourMa 

Title: LST algorithm developments accumulated during integration PR

Description:

This PR integrates accumulated LST algorithm developments held back during the review of the LST integration (cms-sw/cmssw#45117). The full list of PRs that are included here can be found in https://github.com/SegmentLinking/cmssw/issues/117. This is our first step in our list of follow-up tasks (https://github.com/cms-sw/cmssw/issues/46746).

The changes include bug fixes and algorithmic improvements, but they also start to address follow-up comments from the integration PR. In particular, the LST readme was updated (addressing https://github.com/cms-sw/cmssw/pull/45117#discussion_r1681737544 and https://github.com/cms-sw/cmssw/pull/45117#discussion_r1681741075) and the pT threshold is now configurable (addressing https://github.com/cms-sw/cmssw/pull/45117#discussion_r1749245650).

**Comment by VourMa** [comment]
> Here's a draft for the CMSSW PR. @slava77 @VourMa
> 
> Title: LST algorithm developments accumulated during integration PR
> 
> Description:
> 
> This PR integrates accumulated LST algorithm developments held back during the review of the LST integration ([cms-sw#45117](https://github.com/cms-sw/cmssw/pull/45117)). The full list of PRs that are included here can be found in #117. This is our first step in our list of follow-up tasks ([cms-sw#46746](https://github.com/cms-sw/cmssw/issues/46746)).
> 
> The changes include bug fixes and algorithmic improvements, but they also start to address follow-up comments from the integration PR. In particular, the LST readme was updated (addressing [cms-sw#45117 (comment)](https://github.com/cms-sw/cmssw/pull/45117#discussion_r1681737544) and [cms-sw#45117 (comment)](https://github.com/cms-sw/cmssw/pull/45117#discussion_r1681741075)) and the pT threshold is now configurable (addressing [cms-sw#45117 (comment)](https://github.com/cms-sw/cmssw/pull/45117#discussion_r1749245650)).

Looks good to me! And it also fixes the first bullet point of this https://github.com/cms-sw/cmssw/pull/45117#issuecomment-2479912047.

**Comment by slava77** [comment]
> Here's a draft for the CMSSW PR. @slava77 @VourMa

I'd add a plot from MTV to show the combined impact.

A slightly more expanded summary beyond the list of titles of other PRs would also be more self-contained and clear. Something like
- configurable and improved support of minimal pt for track reconstruction (expanding also to 0.6 GeV)
- several updates to T5 DNN selection now replacing most of the algorithmic/rectangular cuts including notebooks for documentation
- helix-based chi2 in rz improvement for pT5 and introduction for T3 objects
- other improvements and fixes, including developments in the standalone code

Most of these were described in [TRK POG presentation on Sep 9](https://indico.cern.ch/event/1443183/#49-line-segment-tracking-statu)

**Comment by slava77** [comment]
> I'd add ...

@ariostas 
if the [text](https://github.com/SegmentLinking/cmssw/pull/135#issuecomment-2515650953) looks reasonable, please update the CMSSW PR description (it's usually better than a comment deeper in the thread).

Also, should this be made non-draft for our own bookkeeping ?

**Pull request merged**
