### PR TITLE
Fix typo in T3 code

### LINKED ISSUE #43: Port SegmentLinking/TrackLooper#407 here
SegmentLinking/TrackLooper#407

### PR DESCRIPTION
**Pull request by VourMa**
Porting SegmentLinking/TrackLooper#407.

Closes #43.

### CODE REVIEW

**Comment by VourMa** [comment]
> /run all

Tests seem to be skipped. Any idea why? Maybe I don't have the permissions to run them?
The ones started by Gavin in his PR run fine.
image
image

**Comment by ariostas** [comment]
Could you try again to see if it works? Forks on Github work a little different, so I had to add an explicit list of users who can run the CI. I'm not sure why it worked for Gavin.

**Review by slava77 — APPROVED** [review]

**Pull request merged**
